/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package in.co.ad.htmltopdf;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Paths;

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

import org.jsoup.Jsoup;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Document;

public class App {

    private static final String BASE_PATH = "app/src/main/resources";
    private static final String HTML_INPUT = BASE_PATH + "/input.html";
    private static final String PDF_OUTPUT = BASE_PATH + "/input2pdf.pdf";

    public static void toPdf() throws FileNotFoundException, IOException {

        // Document doc = parseHtmlFile();
        Document doc = parseHtmlString();

        try (OutputStream os = new FileOutputStream(PDF_OUTPUT)) {
            String baseUri = FileSystems.getDefault()
                    .getPath(BASE_PATH)
                    .toUri()
                    .toString();
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.withUri(PDF_OUTPUT);
            builder.toStream(os);
            builder.withW3cDocument(new W3CDom().fromJsoup(doc), baseUri);
            builder.run();
        }
    }

    public static Document parseHtmlFile() {
        File inputHTML = new File(HTML_INPUT);

        Document document = null;
        try {
            document = Jsoup.parse(inputHTML, "UTF-8");
        } catch (IOException e) {
            e.printStackTrace();
        }
        document.outputSettings().syntax(Document.OutputSettings.Syntax.xml);
        return document;
    }

    public static Document parseHtmlString() {
        String inputHTML;
        Document document = null;
        try {
            inputHTML = Files.readString(Paths.get(HTML_INPUT));

            document = Jsoup.parse(inputHTML, "UTF-8");
            document.outputSettings().syntax(Document.OutputSettings.Syntax.xml);

        } catch (IOException e) {
            e.printStackTrace();
        }
        return document;
    }

    public static void main(String[] args) {
        System.out.println("----Start----");
        try {
            App.toPdf();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("----End----");
    }
}
